### ISSUE TITLE
[asm] Confusing error if mode is missing

### ISSUE THREAD

**Issue by arthaud** [hugsy/gef#185]
#### Steps to reproduce

```
gef➤  asm -a arm nop
[!] Command 'assemble' failed to execute properly, reason: sequence item 1: expected str instance, NoneType found
```

#### Observed Results

I guess the error is about the missing mode (-m).

#### Expected results

It would be nice to have an explicit error message.

#### Traces

```
── Exception raised
TypeError: sequence item 1: expected str instance, NoneType found
── Detailed stacktrace
↳ File "~/.gdbinit-gef.py", line 5684, in do_invoke()
    →                                                                          ":".join([arch_s, mode_s]),
↳ File "~/.gdbinit-gef.py", line 3197, in invoke()
    →                 self.do_invoke(argv)
── Runtime environment
* GDB: 8.0.1
* Python: 3.6.3 - final
* OS: Linux - 4.13.11-1-ARCH (64bit) on arch  
```

BTW, thank you for making gef. This tool is great. I might contribute whenever I have time.

**Comment by hugsy** [comment]
Good point, I'll add a help option to enumerate the modes available.

**Comment by hugsy** [comment]
Fixed, see commit 457fd20 , `asm -h` now displays something like

![](https://i.imgur.com/BYqzLMc.png)

**Comment by arthaud** [comment]
FWIW, forgetting the "-m" option still throws an ugly error "expected str instance, NoneType found" to the user.

I made PR #187 to improve this.
